#device_placement: "cpu"

# model/tokenizer
model_name: "decapoda-research/llama-7b-hf" # add model here
tokenizer_name: "gpt2" # add model here
gradient_checkpointing: true
save_name: "save_folder/gpt4all_str2plusallti" # CHANGE 

# dataset
streaming: false
num_proc: 32
dataset_path: "configs/deepspeed/tbldailyAShareSTR2Plus_RAWSUM_forGPT10percentTestTI_prepared_train.jsonl" # update
max_length: 1024
batch_size: 32

# train dynamics
lr: 5.0e-5
eval_every: 800
eval_steps: 100
save_every: 800
output_dir: "model_data/gpt4all_str2plusallti" # CHANGE
checkpoint: null
lora: false
warmup_steps: 100
num_epochs: 2

# logging
wandb: true
wandb_entity: "maxtensor" # update
wandb_project_name: "gpt4all_str2plusallti" # update
seed: 42

